

---
spring:
  profiles: prod

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/kitchenapp
    username: kitchenapp
    password: VZa4u&VjFnRXn&!F62bQ
  flyway:
    url: jdbc:mysql://localhost:3306/kitchenapp
    user: kitchenapp
    password: VZa4u&VjFnRXn&!F62bQ
    enabled: false
    baseline-on-migrate: true

---
spring:
  profiles: test