spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:sqlserver://kitchenappdb.database.windows.net:1433;database=kitchenapp;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: kitchenapp@kitchenappdb
    password: <REMOVED>
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
jwt:
  secret: <REMOVED>
  expiry: 86400000
---

jwt:
  secret: 8syTLFk=vARDWkpHD#5E
  expiry: 86400000
spring:
  profiles: local
  datasource:
    url: jdbc:sqlserver://localhost;database=kitchenapp
    username: kitchenapp
    password: VZa4u&VjFnRXn&!F62bQ
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer;DB_CLOSE_ON_EXIT=false;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: kitchenapp
    password: VZa4u&VjFnRXn&!F62bQ
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
jwt:
  secret: 8syTLFk=vARDWkpHD#5E
  expiry: 86400000