spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:sqlserver://kitchenappdb.database.windows.net:1433;database=kitchenapp;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: kitchenapp@kitchenappdb
    password: <REMOVED>
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
---
spring:
  profiles: local
  datasource:
    url: jdbc:sqlserver://localhost;database=kitchenapp
    username: kitchenapp
    password: VZa4u&VjFnRXn&!F62bQ
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  security:
    user:
      name: test
      password: 1234

---
spring:
  profiles: test