spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true

---
spring:
  profiles: prod
  datasource:
    url:
    username:
    password:
    driver-class-name:

---
spring:
  profiles: local
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/kitchenapp
    username: kitchenapp
    password: VZa4u&VjFnRXn&!F62bQ
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: test